[versions]
agp = "8.3.2"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.9.0"
compose = "1.6.5"
compose-plugin = "1.6.2"
kotlin = "1.9.23"
androidx-compose-test = "1.6.5"
arrow = "1.2.4"
koin = "3.5.6"
koin-compose = "1.1.5"
store = "5.1.0-alpha02"
multiplatform-settings = "1.1.1"
kermit = "2.0.3"
assertk = "0.28.1"
ksp = "1.9.23-1.0.20"
mockative = "2.2.0"


[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-compose-junit4 = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "androidx-compose-test" }
androidx-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-test" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
store = { module = "org.mobilenativefoundation.store:store5", version.ref = "store" }
multiplatformSettings-noArgs = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
multiplatformSettings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatform-settings" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
mockative = { module = "io.mockative:mockative", version.ref = "mockative" }
mockative-processor = { module = "io.mockative:mockative-processor", version.ref = "mockative" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
allOpen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }